const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright-core');
const { findBrowser } = require('../../lib/hopebox-session.cjs');
const { pathToFileURL } = require('node:url');
const dir = path.resolve(__dirname, '../../projects/2026-09-candle21-commerce/preview');
(async () => {
  const browser = await chromium.launch({ executablePath: findBrowser(), headless: true });
  try {
    const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
    await context.route(/^https?:/, route => route.abort());
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.goto(pathToFileURL(path.join(dir, 'index.html')).href);
    assert.equal(await page.locator('[role=tab]').count(), 4);
    await page.getByRole('tab', { name: '商品選款', exact: true }).click();
    assert.equal(await page.locator('#preview').getAttribute('src'), 'product.html');
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: path.join(dir, 'review-mobile.png'), fullPage: true });
    await page.goto(pathToFileURL(path.join(dir, 'product.html')).href);
    const button = page.locator('.single_add_to_cart_button');
    assert.equal(await button.isDisabled(), true);
    const input = page.locator('.hlc21-picker input[type=number]').first();
    await input.fill('20'); assert.match(await page.locator('.hlc21-total').innerText(), /還差 1/u);
    await input.fill('21'); assert.equal(await button.isEnabled(), true);
    await page.locator('.hlc21-picker input[type=number]').nth(1).fill('1'); assert.equal(await button.isDisabled(), true);
    await page.locator('.hlc21-picker input[type=number]').nth(1).fill('0');
    await input.fill('-1'); assert.equal(await button.isDisabled(), true);
    await input.fill('21');
    assert.equal(await input.evaluate(e => getComputedStyle(e).fontSize), '16px');
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: path.join(dir, 'product-mobile.png'), fullPage: true });
    await page.goto(pathToFileURL(path.join(dir, 'admin.html')).href);
    const name = page.locator('[name="c21[names][peaceful-night][name]"]');
    await name.fill(' '); assert.equal(await name.evaluate(e => e.checkValidity()), false);
    await name.fill('安然入夜'); assert.equal(await name.evaluate(e => e.checkValidity()), true);
    const days = page.locator('[name="c21[consultation][days]"]');
    await days.fill('-1'); assert.equal(await days.evaluate(e => e.checkValidity()), false); await days.fill('30');
    await page.setViewportSize({ width: 1280, height: 900 });
    await page.screenshot({ path: path.join(dir, 'admin-desktop.png'), fullPage: true });
    await page.goto(pathToFileURL(path.join(dir, 'landing.html')).href);
    assert.equal(await page.locator('a[href*="product.html"]').count() > 0, true);
    assert.equal((await page.content()).includes('[hopelight_c21'), false);
    await page.screenshot({ path: path.join(dir, 'landing-desktop.png'), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    const overflow = await page.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth, nodes: [...document.querySelectorAll('body *')].filter(e => e.getBoundingClientRect().right > innerWidth + 1 && getComputedStyle(e).position !== 'fixed').slice(0, 8).map(e => ({ tag: e.tagName, class: e.className, width: e.getBoundingClientRect().width })) }));
    if (overflow.scroll > overflow.width) console.log(await page.locator('.table-wrap').evaluate(e => ({overflow: getComputedStyle(e).overflowX, width: e.clientWidth, scroll: e.scrollWidth, parent: e.parentElement.tagName, headStyleCount: document.styleSheets.length})));
    assert.equal(overflow.scroll <= overflow.width, true, JSON.stringify(overflow));
    await page.screenshot({ path: path.join(dir, 'landing-mobile.png'), fullPage: true });
    const noJs = await browser.newContext({ javaScriptEnabled: false, viewport: { width: 390, height: 844 } });
    const plain = await noJs.newPage();
    await plain.goto(pathToFileURL(path.join(dir, 'product.html')).href);
    assert.equal(await plain.locator('.hlc21-picker input[type=number]').count(), 10);
    assert.equal(await plain.locator('.single_add_to_cart_button').isEnabled(), true);
    assert.deepEqual(errors, []);
    console.log('PASS Chromium: total controls, malformed fields, 16px inputs, mobile overflow, LP links, no-JS fields, no page errors. Screenshots saved.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
